"""Connector for voledge.

voledge is a single-underlying (default SPY) delta-hedged options strategy,
backtest-only, with no persisted "current position" concept anywhere in its
codebase (P&L is computed inline day-by-day in strategy/delta_hedge.py and
never saved as a snapshot). Unlike pairtrade-lab-1 (which replays a specific
historical fill history as its stand-in -- see that connector), voledge's
actual strategy signal (strategy/signal.py::compute_signal) is inherently
point-in-time: it flags contracts on the CURRENT real options chain as
rich/cheap relative to the current fitted vol surface, not a position held
over time.

So the disclosed stand-in here (`connectors/standins/voledge_positions.json`)
was generated by running voledge's own, unmodified pipeline -- fetching the
real, current SPY chain (data/options.py, live yfinance/Alpaca),
extract_implied_vol, fit_vol_surface, compute_signal, exactly as voledge's
own backtest/precompute_results.py does for its committed results -- and
computing each flagged contract's real Black-Scholes Greeks via
greeks/analytical.py::black_scholes_greeks. Each flagged contract is treated
as a hypothetical 1-contract position (long if "cheap", short if "rich").
compute_signal flagged 548 contracts at its default min_edge=0.02; only the
top 20 by |edge_vol_points| are kept here (a disclosed cap for aggregation
practicality -- see the JSON's "n_signal_contracts_total" and
"_disclosure" fields), not a claim the rest aren't real signals.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

from connectors.schema import AssetClass, Counterparty, DataProvenance, Position, SourceMeta

REPO = "voledge"
STANDIN_FILE = Path(__file__).parent / "standins" / "voledge_positions.json"


def fetch_positions() -> tuple[list[Position], SourceMeta]:
    if not STANDIN_FILE.exists():
        return [], SourceMeta(
            repo=REPO,
            read_from=str(STANDIN_FILE),
            provenance=DataProvenance.BACKTEST_STANDIN,
            as_of=dt.datetime.now(dt.timezone.utc),
            n_positions=0,
            notes=f"{STANDIN_FILE} not found; no stand-in snapshot has been generated yet.",
        )

    with STANDIN_FILE.open() as f:
        data = json.load(f)

    generated_at = dt.datetime.fromisoformat(data["generated_at"])
    positions = [
        Position(
            strategy=REPO,
            asset=f"{data['ticker']} {row['expiry'][:10]} {row['option_type'][0].upper()}{row['strike']:g}",
            quantity=float(row["quantity"]),
            market_value=None,
            asset_class=AssetClass.OPTION,
            counterparty=Counterparty.NONE,
            provenance=DataProvenance.BACKTEST_STANDIN,
            as_of=generated_at.date(),
            strategy_tag=row["direction"],
            greeks=row["greeks"],
            extra={
                "underlying": data["ticker"],
                "strike": row["strike"],
                "expiry": row["expiry"],
                "days_to_expiry": row["days_to_expiry"],
                "entry_iv": row["entry_iv"],
                "fair_iv": row["fair_iv"],
                "edge_vol_points": row["edge_vol_points"],
            },
        )
        for row in data["positions"]
    ]
    return positions, SourceMeta(
        repo=REPO,
        read_from=str(STANDIN_FILE),
        provenance=DataProvenance.BACKTEST_STANDIN,
        as_of=generated_at,
        n_positions=len(positions),
        notes=(
            f"Disclosed stand-in (not a live position): {data['n_signal_contracts_total']} "
            f"contracts flagged by voledge's own compute_signal() on the real, current "
            f"{data['ticker']} chain as of {data['generated_at']}; top {len(positions)} kept "
            "by |edge_vol_points|. See module docstring."
        ),
    )
